apiVersion: apps/v1
kind: Deployment
metadata:
  name: beatsheet-service
  labels:
    app: beatsheet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: beatsheet
  template:
    metadata:
      labels:
        app: beatsheet
    spec:
      containers:
      - name: beatsheet
        image: go2mars2030/beatsheet:latest
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: beatsheet-secret
              key: database_url
